create table if not exists public.agency_competitor_reports (
    id bigint generated by default as identity primary key,
    owner_telegram_id bigint not null,
    competitor_name text not null,
    website text,
    report_markdown text not null,
    sources jsonb not null default '[]'::jsonb,
    verdict text not null default 'НАБЛЮДАТЬ',
    checked_at timestamptz not null default now(),
    created_at timestamptz not null default now()
);

create index if not exists agency_competitor_reports_owner_checked_idx
    on public.agency_competitor_reports (owner_telegram_id, checked_at desc);

alter table public.agency_competitor_reports enable row level security;

-- Приложение работает с серверным SUPABASE_SECRET_KEY.
-- Для anon/authenticated прямого доступа к таблице не открываем.
